# Auto-Generated by device/xiaomi/vendor_detect/../vendor_detect/setup.sh
PRODUCT_MAKEFILES += $(LOCAL_DIR)/derp derp derp derp derp derp derp derp derp derp derp derp derp derp derp derp derp derp derp derp derp derp derp derp_...mk
