DEVICE=$2
if [ -z "$DEVICE" ]; then
	echo "E: DEVICE not set"
	exit 1
fi
DEV=${LOCAL_PATH}/../$DEVICE
VENDOR=$(cat ${LOCAL_PATH}/vendor_name)
if [ ! -z $VENDOR ]; then
	VENDOR=aosp
fi

TARGET_ANDROIDPRODUCTS=${DEV}/AndroidProducts.mk
TARGET_DEVICEMK=${DEV}/"$VENDOR"_${DEVICE}.mk

if [ ! -z $DEBUG ]; then
	echo "TARGET_ANDROIDPRODUCTS $TARGET_ANDROIDPRODUCTS"
	echo "TARGET_DEVICEMK $TARGET_DEVICEMK"
fi

# Generate AndroidProducts.mk
echo "# Auto-Generated by ${LOCAL_PATH}/setup.sh" > $TARGET_ANDROIDPRODUCTS
echo "PRODUCT_MAKEFILES += \$(LOCAL_DIR)/"$VENDOR"_${DEVICE}.mk" >> $TARGET_ANDROIDPRODUCTS

# Change <vendor>_${DEVICE}.mk
ORIGIN_DEVICEMK=$(ls $DEV/*_$DEVICE.mk)

if [ -z "$ORIGIN_DEVICEMK" ]; then
	echo "Please add default makefile to change"
	exit 1
fi
sed -i '/\/common/d' "$ORIGIN_DEVICEMK"
sed -i '/PRODUCT_NAME/d' "$ORIGIN_DEVICEMK"

if test -f vendor/"$VENDOR"/config/common_full_phone.mk; then
	echo "\$(call inherit-product, vendor/"$VENDOR"/config/common_full_phone.mk)" >> "$ORIGIN_DEVICEMK"
elif test -f vendor/"$VENDOR"/config/common.mk; then
	echo "\$(call inherit-product, vendor/"$VENDOR"/config/common.mk)" >> "$ORIGIN_DEVICEMK"
else
	if [ ! -z $DEBUG ]; then
		echo "\$(call inherit-product, vendor/"$VENDOR"/config/common.mk)" >> "$ORIGIN_DEVICEMK"
	else
		echo "Not valid vendor"
		exit 1
	fi
fi
echo "PRODUCT_NAME := ${VENDOR}_${DEVICE}" >> "$ORIGIN_DEVICEMK"
mv $ORIGIN_DEVICEMK $TARGET_DEVICEMK
